<?php

namespace Fwk\Security\User\Providers;

class TestUser implements \Fwk\Security\User
{
    protected $identifier;
    protected $username;
    
    public function __construct($identifier, $username) {
        $this->identifier = $identifier;
        $this->username   = $username;
    }
    
    public function getIdentifier() {
        return $this->identifier;
    }
    
    public function getUsername() {
        return $this->username;
    }
}

/**
 * Test class for Memory.
 * Generated by PHPUnit on 2013-01-24 at 02:00:13.
 */
class MemoryTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Memory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Memory();
    }

    /**
     */
    public function testAdd() {
        $this->assertEquals(0, $this->object->count());
        $user = new TestUser(1, 'joe2083');
        $this->object->add($user);
        $this->assertTrue($this->object->has($user));
        $this->assertEquals(1, $this->object->count());
    }

    /**
     */
    public function testRemove() {
        $user = new TestUser(1, 'joe2083');
        $user2 = new TestUser(2, 'bar201');
        $this->assertFalse($this->object->has($user));
        $this->object->add($user);
        $this->assertTrue($this->object->has($user));
        $this->object->remove($user);
        $this->assertFalse($this->object->has($user));
    }

    /**
     */
    public function testGetById() {
        $user = new TestUser(1, 'joe2083');
        $this->object->add($user);
        
        $this->assertEquals($user, $this->object->getById(1));
        $this->setExpectedException('\Fwk\Security\Exceptions\UserNotFound');
        $this->object->getById(2);
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testGetByUsername().
     */
    public function testGetByUsername() {
        $user = new TestUser(1, 'joe2083');
        $this->object->add($user);
        
        $this->assertEquals($user, $this->object->getByUsername('joe2083'));
        
        $this->setExpectedException('\Fwk\Security\Exceptions\UserNotFound');
        $this->assertEquals($user, $this->object->getByUsername('Joe2083', false));
    }
}